import type { Metadata } from "next";
import Header from "@/src/components/dashboardLayout/Header";
import SideNav from "@/src/components/dashboardLayout/SideNav";
import Main from "@/src/components/dashboardLayout/Main";
// import FootPagination from "@/src/components/dashboardLayout/FootPagination";

export const metadata: Metadata = {
  title: "Excite Enterprise CRM Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Main>{children}</Main>;
}

/* 

<main className="w-screen h-screen">
      <SideNav />

      <section className="h-screen w-4/5">
        <Header />

        {children}
      </section>
    </main>*/
