import type { Metadata } from "next";
import Header from "@/src/components/dashboardLayout/Header";
import SideNav from "@/src/components/dashboardLayout/SideNav";
import FootPagination from "@/src/components/dashboardLayout/FootPagination";

export const metadata: Metadata = {
  title: "Excite Enterprise CRM Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className='w-screen h-screen'>
      <section className='flex'>
        <aside className='h-screen w-1/5 bg-[#101828]'>
          <SideNav />
        </aside>
        <section className='h-screen w-4/5'>
          <nav className="h-12 border w-full">
            <Header />
          </nav>
          <section className={`antialiased h-[calc(100vh-96px)]`}>{children}</section>
          <footer className="h-12">
            <FootPagination />
          </footer>
        </section>
      </section>
    </main>
  );
}

